### ISSUE TITLE
Clicking anywhere outside of the app should close it.

### ISSUE THREAD

**Issue by irctrakz** [djp952/hdhomeruntray#31]
Currently, the only way to close the app (on Windows 10 anyway) is to click on the unpin icon.

Would be super useful if clicking anywhere outside of the app also caused it to close.

**Comment by djp952** [comment]
I actually tried (and failed) to do that but will try again!  The technical difficulty was that there is no main "window" that can be used to track if the mouse is in or out, other than the little itty bitty one that hosts the tray icon itself.  The other windows are all pop-ups.  I think it can be done, but requires a lot of plumbing changes.

This would probably be optional anyway, understanding there is ZERO documentation yet and you'd have no way to know this, one of the primary motivations for the application was that it could sit on top of a running non-full-screen Windows Media Center, HDHomeRun VIEW, or Kodi instance and the user could still interact with those applications without collapsing everything.

Will do what I can for ya, not sure on a timeline, though.  Thank you!

**Comment by irctrakz** [comment]
Closing it if the mouse cursor moves away from the window would be good?

Thanks for building this, it's really useful and awesome.

**Comment by djp952** [comment]
Did you know if you "hover" over the tray icon you get that behavior?  You can't open the detailed device info that way, you have to "pin" it first since once the mouse leaves the tray icon that closes.  Hmmmm.... what if the application were to remember that you had something open last time it was unpinned, and auto-open that again on a tray icon hover?  Like if you were watching device 1234ABCD when you last unpinned, you'd get both the LED view and device 1234ABCD open without clicking on anything?  That might be cool, if it's of value :)

**Comment by irctrakz** [comment]
If you use Steam, that pretty much has the exact behavior that I'm talking about.

**Comment by djp952** [comment]
Hi **irctrakz**, I got this mostly working, but have a couple questions as to what your expectations are:

- What do you feel should happen if you click a hyperlink in the application that opens a browser (device IP address / update available / LICENSE)?  Do you feel this action should implicitly "unpin" or should a _subsequent_ loss of input focus cause an implicit "unpin"?
- What do you feel should happen if the loss of input focus was caused by a click on the tray icon itself?  This one is a little tricky since the as-is code would already cause an "unpin", but I would need to watch for that and handle it differently.  If you're good with a click on the tray icon still causing an "unpin" it's just a transparent special case to handle internally.

It seems to work quite well so far by propagating any child (device form/settings form) "Deactivate" events to the popup form, and if the mouse cursor doesn't happen to be in the popup form, go ahead and automatically "unpin".  Other than clicking on hyperlinks in the device form, all mouse interactions take place on the popup form.

Thanks in advance!

**Comment by irctrakz** [comment]
Love it! That sounds pretty much perfect.

I think a click is really an intentioned event, and clicking anywhere that isn't on the dialog or icon itself should cause the modal to close (so same for both on the bar itself - if you open a browser window for example, OR click anywhere inside the task bar).

Clicking on the taskbar icon itself should probably do nothing if it's already open?

**Comment by djp952** [comment]
Would you mind taking a run at a test build for this: https://1drv.ms/u/s!AgEGEEVzGNq-jLMYyFnb0nbGTqR85Q?e=SOe8zg.  (OneDrive)?  I'm not convinced the behavior is right if you happen to click on the actual Tray Icon itself (it will unpin and then re-pin), but I'd like you opinion as to how much this meets your expectations.

There is a new setting to control this; "Unpin Automatically", which I defaulted to "Disabled".  So you'll need to install, run, pin, open settings, and change that to "Enabled" first.  The setting should stick immediately, though.

Thank you in advance for any feedback you can provide before making this change "official" :)

**Comment by irctrakz** [comment]
Dude! That's perfect! Love it!!!

**Comment by irctrakz** [comment]
I see what you mean about the "if you happen to click on the actual Tray Icon itself (it will unpin and then re-pin)", interesting. Maybe a toggle?

**Comment by djp952** [comment]
I can just exclude the area of the screen where the icon is from the test so the click would unpin via the existing mechanism.  Otherwise you're good with how it works?

**Comment by irctrakz** [comment]
100% it's great! Thank you again.

**Comment by djp952** [comment]
Great! Let's call it "implemented" via https://github.com/djp952/hdhomeruntray/commit/11f3b80e17f8d98f9b022720ccf752a08bf3903d and https://github.com/djp952/hdhomeruntray/commit/1a002792493e483370dea8e985071a23686add3e.

Will test a few more times on Windows 7 and Windows 10 as well, I saw an unhandled exception the first time it was run on Windows 7, but I think that was due to upgrading from a really old version (0.2.x).
