### ISSUE TITLE
System icon does not appear after x64 install

### ISSUE THREAD

**Issue by marknoble** [djp952/hdhomeruntray#36]
After installing hdhomerunstatusmonitor-0.9.2.8029-x64.msi the icon did not appear in the system tray.

I assume just running the MSI is all that's required, but it'd be helpful to include install steps in the wiki here:
https://github.com/djp952/hdhomeruntray/wiki

I'd be happy to help with documentation once I get it working.
____________
Edition	Windows 10 Pro
Version	21H2
Installed on	‎2021-‎11-‎26
OS build	19044.1415
Experience	Windows Feature Experience Pack 120.2212.3920.0

**Comment by djp952** [comment]
Not sure I follow, exactly.  After installing, did you run it?  It doesn't run automatically.  Depending on the OS the steps to "dock" the tray icon are also different, and those steps are intended to be in the wiki when I get there :)

If you think there should be a "launch after installation" check box in the installer, that could be done.

If you just didn't run it, you should see "HDHomeRun Status Monitor" in your Start, give it a go!  I think Windows 10 will temporarily dock a tray icon the first time you run it, but it will auto-hide on you on subsequent runs.  You'll need to go into Taskbar Settings to force it to stay docked, if that's what you want.

**Comment by djp952** [comment]
How's this for a basic placeholder to be improved upon later: https://github.com/djp952/hdhomeruntray/wiki/Installation-(Windows-10)

I'll get to a page for Windows 11 later today.

**Comment by marknoble** [comment]
I guess I didn't run it, so yeah, I'd expect after installing that it starts running and is visible in the tray out of the gate.

The documentation looked good.

**Comment by djp952** [comment]
I know you closed this, but I did take the concern seriously and implemented it via https://github.com/djp952/hdhomeruntray/commit/eee6b1d58b0d46f094a324cb24ba8b61a2c835b1.  Moving forward, there will be a checkbox on the setup "finish" page that says "Launch HDHomeRun Status Monitor" and it will default to checked.

Just wanted to let you know that the feedback wasn't written off on this end, just didn't have the time to do anything about it recently. Once the next "beta" is released I'll of course update the installation wiki pages.  I also figured out how to make them not look so egregiously bad :)

I do **sincerely** appreciate the feedback, and action has been taken my friend :) Thank you for trying the application out in the first place, especially since it's still semi-private!!
