### ISSUE TITLE
Have it open at the bottom-right even though I'm "one of those" using a top taskbar

### ISSUE THREAD

**Issue by jkr4m3r** [djp952/hdhomeruntray#44]
Title sums it up pretty much, and yes I realize Win11 uses a hack to get the top taskbar. Plan on using Win10 for a while, I'm sure many people use older operating systems for their home theater stuff.

Main issue is settings and pop-ups open out of the top of the screen.

**Comment by djp952** [comment]
I agree with you on this, and will definitely figure out a solution at some point.  To that end, I don't think this is a "blocking issue" for a legit "1.0.0" release and intend to deal with it when I get around to https://github.com/djp952/hdhomeruntray/issues/26 :)

I am not a fan of the "perpetual betas" model and think this needs a formal release sooner rather than later; I'm working on the accessibility issues that came up, which I feel are blocking.  I hope you don't mind if I kick this one down the road a bit?

**Comment by jkr4m3r** [comment]
Oh hell, take as long as needed, this is always a low priority problem for all Windows devs. I'm just tickled the project came to fruition in any form.

MS proved their disdain for top-taskbar-users with Win 11, I'm sure it's a pain for devs much more than for me. :P

**Comment by djp952** [comment]
Question for you while I think about how to implement this along with the related concerns to address, do you envision the "popup" continuing to use a horizontal stack if your tray is docked on the left or right, or do you think a vertical stack would be more appropriate?

If you can excuse the crudity of these pathetic mock-ups (I didn't have time to build it to scale or paint it):

BOTTOM:
![bottom](https://user-images.githubusercontent.com/706055/148877315-0569735a-f266-4db8-b6ee-7f37930871cb.png)

TOP:
![top](https://user-images.githubusercontent.com/706055/148877319-5f265615-3234-428b-b2b3-a6fe6a66afec.png)

LEFT:
![left](https://user-images.githubusercontent.com/706055/148877326-729a3c6b-93fc-4ace-ad45-4477b78b651d.png)

RIGHT:
![right](https://user-images.githubusercontent.com/706055/148877379-9c01fadf-482b-43af-9ddb-c39eba9f5e5d.png)

Another option for left/right would be to use the boundaries of the workspace and keep the stack horizontal:

LEFT:
![left2](https://user-images.githubusercontent.com/706055/148877564-d9cc7fe5-b9e4-4979-b5d3-5a42508a1ff2.png)

RIGHT:
![right2](https://user-images.githubusercontent.com/706055/148877573-6847b3bb-d810-4798-92e1-6bbf2b12acfd.png)

One reason I linked this with Issue 26 (https://github.com/djp952/hdhomeruntray/issues/26) is that I see a need to be able to alter how the "stacking" works if there are too many things to show horizontally on the user's screen.  For that I wasn't envisioning a vertical stack, more of a multi-row horizontal stack, but wanted to see what you think it ultimately "should" look like for the left/right system tray cases.

I kind of like leaving it horizontal like in the second set of screen shots above, but I've always been a "bottom taskbar" person, so that's where my head tends to go. If you think a vertical design would look best for these cases, I'm on board.

I hope you don't mind being involved in any design decisions like this, it's kind of how I roll, doubly so for features I wouldn't have thought of on my own.

**Comment by jkr4m3r** [comment]
I like the way it looks in the last 2 shots, at the bottom, horizontal. In
my case, with a top taskbar, it looks fine at the top but the settings etc
pop up, off the screen.

As long as the settings pop in the correct direction I'm fine with any
scenario, hell, 4 dots on the icon tray would suffice for my needs.

**Comment by djp952** [comment]
Reclassified as a "bug", not seeing the form at all is definitely something that needs to be addressed.  I got as far as detecting where the taskbar "is" tonight, which is 75% of the battle on Win 7 / Win 10 :)

**Comment by djp952** [comment]
Hi @jkr4m3r, I'm about halfway done with this (so far so good) but ran into hopefully one last question to ask.  If the system tray is docked on the **Left**, do you think that it's OK to leave the ordering of the controls on a "pinned" popup as [DEVICE|DEVICE|DEVICE|SETTINGS|UNPIN] the way they are, or should they be reversed as [UNPIN|SETTINGS|DEVICE|DEVICE|DEVICE]?

To me, leaving it as-is seems fine, perhaps even 'correct', but I'm also not one to move my taskbar around so I would appreciate your input.

**Comment by djp952** [comment]
Eh, you don't need to answer that.  Let's leave it this way unless someone that likes a left taskbar complains.  I think it's fine.  Let's call this "implemented via https://github.com/djp952/hdhomeruntray/commit/40a273c75a5dc5af3128cb4df7a0c7db41f2cc60" and revisit if necessary!

Here is how it turned out:
![top](https://user-images.githubusercontent.com/706055/149628709-6870a9e9-865a-4203-bcfe-873f116e8922.png)
![left](https://user-images.githubusercontent.com/706055/149628711-346e490d-2ac3-4220-8f67-5ee989826e20.png)
![right](https://user-images.githubusercontent.com/706055/149628712-9aaebe69-1dc1-468e-ae7c-edadb4d59c5c.png)

Thanks for the request! It's a better application for it.
