### ISSUE TITLE
[Request] IP Address to Hostname

### ISSUE THREAD

**Issue by arrmo** [djp952/hdhomeruntray#71]
Hi,

One item that would be nice - the option to show the hostname of the tuner, instead of the IP address (particularly helpful with more than one tuner).

Thanks!

**Comment by arrmo** [comment]
FYI, turns out getting the hostname is pretty straightforward ... I'm just a bit confused where to store it, how to display it 😞. Here is how to get the hostname (confirmed to work),
```
String^ dnsname = (Dns::GetHostEntry(ipaddress)->HostName) -> Split('.')[0];
```

**Comment by djp952** [comment]
I need to apologize here, it seems that my gmail account was messed up on my phone, which I kind of rely upon for e-mails. I think I missed a great deal of things?I am not ignoring this, but I am behind the proverbial 8-ball on it, and I sincerely apologize for that. This is on me. I did recently try to enable IPv6 on my NAS (Where HDHomeRun RECORD lives here), but found it to be “no beuno” to date. I was unable to get IPv6 discovery info from that particular node with IPv6 enabled? My router is also still set up for just IPv4, and my “backbone” switch needs to be replaced as it’s clearly End-Of-Life (8 years old) and is causing a lot of weird problems for me right now. I am legit “all good” with anyone deciding to Fork this project and make it their own. To that end, I have a lot of Windows Forms and “Dark Mode” support that I have not brought forward into this project yet, but (very) seriously, if you feel you are in a position to own this moving forward, I am legit good with it, and offer my support?I am extremely behind on pretty much all aspects of my life right now, and I don’t think that condition will abate until at least August/September 2023.Short version – if you, or anyone else you know, want to take this over and make it better, I would be 100% on board with that 😊 If not, there is currently a semi-protracted “wait period” and an author’s inability to get IPv6 to actually work?  From: Russell MorrisSent: Friday, April 7, 2023 4:06 PMTo: djp952/hdhomeruntrayCc: SubscribedSubject: Re: [djp952/hdhomeruntray] [Request] IP Address to Hostname (Issue #71) FYI, turns out getting the hostname is pretty straightforward ... I'm just a bit confused where to store it, how to display it 😞. Here is how to get the hostname (confirmed to work),String^ dnsname = (Dns::GetHostEntry(ipaddress)->HostName) -> Split('.')[0];—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

**Comment by arrmo** [comment]
No worries at all, fully understand. In a similar situation here, more than willing to help if I can.

I'll fork this, make my updates, and submit a PR ... OK with you? That way the updates go in, but you can review and control them. Again, more than willing to help.

Thanks!!

**Comment by arrmo** [comment]
Created PR #72

**Comment by arrmo** [comment]
Closing this item - track in the PR 😄

**Comment by djp952** [comment]
Are you in a position to potentially take this project over and move it forward? I have never found any personal use-case for this project and it was created due to end-user requests of my PVR addon only. I am 100% cool with letting it go?

**Comment by arrmo** [comment]
I would - except Frontier recently announced they are whacking my CableCARD. Let me see if I can find another option!

**Comment by djp952** [comment]
I sincerely hope that you are able to navigate that problem; but it sadly also does lend credence to why I feel this project was doomed to failure from its onset?

**Comment by arrmo** [comment]
Agreed! But HomeRun is more than just CableCARD!
